FROM ubuntu:20.04
ARG UID=<UID>
ENV USER=<USER>
# Configure Timezone
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg --add-architecture i386 && \
    apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y dist-upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
               sudo vim-gtk3 wget inkscape bc \
               rsync kmod execstack sqlite3 libsqlite3-dev libzstd-dev:i386 \
               libzstd-dev cmake lib32z1-dev unar inkscape imagemagick \
               subversion git bc wget sudo ccache gcc g++ binutils autoconf automake \
               autopoint libtool-bin make bzip2 libncurses5-dev libreadline-dev \
               zlib1g-dev flex bison patch texinfo tofrodos gettext pkg-config \
               ecj fastjar perl libstring-crc32-perl ruby gawk python \
	       bsdmainutils sudo locales \
               libusb-dev unzip intltool libacl1-dev libcap-dev libc6-dev-i386 \
               lib32ncurses5-dev gcc-multilib lib32stdc++6 libglib2.0-dev && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
               sqlite3:i386 && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

# Create the user
RUN useradd -m -u ${UID} -G sudo -s /bin/bash "${USER}" && passwd --delete "${USER}"
WORKDIR /home/${USER}
# ... and make sure file permissions are ok
RUN echo umask 0022 >> .bashrc

USER "${USER}"
CMD ["/drun.sh"]
